README.md
This brings our README in line with the blog post and the getting started guides in App O11y.
This makes it easier for customers to get started without doing any agent or collector setup.
=> Change Getting Started to send to Grafana Cloud via OTLP

CHANGELOG.md, src/Grafana.OpenTelemetry.Base/Instrumentations/AspNetInitializer.cs
Updates ASP.NET instrumentation type name. Previously was looking in the Trace namespace when activating metrics.
=> Update ASP.NET instrumentation type name

CHANGELOG.md, src/Grafana.OpenTelemetry.Base/Instrumentations/OwinInitializer.cs, src/Grafana.OpenTelemetry.Base/ReflectionHelper.cs
Updates OWIN tracing instrumentation reflection lookup strategy. The method overload definition in the OWIN instrumentation causes one method to be exposed with the signature:
```csharp
public static TracerProviderBuilder AddOwinInstrumentation(
this TracerProviderBuilder builder,
Action<OwinInstrumentationOptions> configure = null)
```
[Original file](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/main/src/OpenTelemetry.Instrumentation.Owin/TracerProviderBuilderExtensions.cs
)
The other instrumentations typically expose two methods:
1. One argument (TracerProviderBuilder )
2. Two arguments (TracerProviderBuilder, configuration action)
The `=>` syntax used upstream to define the method overload causes the compiler to only generate the second method signature, with the …
=> Updates reflection lookup / OWIN tracing instrumentation

CHANGELOG.md, src/Grafana.OpenTelemetry.Base/GrafanaOpenTelemetryResourceDetector.cs, tests/Grafana.OpenTelemetry.Tests/TracerProviderExtensionsTest.cs
* `telemetry.distro.name` is hardcoded to "grafana-opentelemetry-dotnet", which I think is more in line with conventions around `telemetry` attributes and is easier readable then `Grafana.OpenTelemetry.Base`.
* `telemetry.distro.version` is set to the file version (e. g. "0.6.0-beta.1"), which is different from the assembly version ("0.0.0.0").
=> Improve values for distro name and version attributes

CHANGELOG.md, tests/Grafana.OpenTelemetry.Tests/Grafana.OpenTelemetry.Tests.csproj
Fixes #49 
Including `xunit.runner.visualstudio` (despite warnings on non-.NET Framework platforms), as this makes the test runner work on all platforms.
=> Include the Visual Studio test runner for all build targets

docs/configuration.md, docs/installation.md
Fixes grafana/app-o11y#506
* Replace the existing "Adding instrumentations" (using AspNet as an example) with "Adding instrumentations not supported by the distribution" (using EventCounters as example), to make it clear customers can use instrumentation libraries not contained in the distro.
* Add a section "Minimizing unneeded dependencies" to the installation documentation, highlighting how lazy-loading can be utilized to minimize dependencies by manually picking needed instrumentation libraries.
=> Add documentation of how to minimize package dependencies

CHANGELOG.md, docs/configuration.md, src/Grafana.OpenTelemetry.Base/GrafanaOpenTelemetryResourceDetector.cs, src/Grafana.OpenTelemetry.Base/GrafanaOpenTelemetrySettings.cs, tests/Grafana.OpenTelemetry.Tests/TracerProviderExtensionsTest.cs
Fixes #57
This adds a dictionary `GrafanaOpenTelemetrySettings.ResourceAttributes`, which allows specifying custom resource attributes which will be applied the `ResourceBuilder` set on provider builders.
This ensures a consistent resource configuration for traces, logs, and metrics.
=> Allow specifying custom resource attributes via `GrafanaOpenTelemetrySettings`

.github/workflows/unit-tests.yml, CHANGELOG.md, global.json, src/Grafana.OpenTelemetry.Base/Grafana.OpenTelemetry.Base.csproj, src/Grafana.OpenTelemetry/Grafana.OpenTelemetry.csproj, tests/Grafana.OpenTelemetry.Tests/Grafana.OpenTelemetry.Tests.csproj
Adds build and test runs for .NET 8.
=> Add support for .NET 8

.markdownlint.yaml, CHANGELOG.md, src/Grafana.OpenTelemetry.Base/GrafanaOpenTelemetryResourceDetector.cs
Fixes #65
Fixes #64 
This follows the same approach taken in the upstream OpenTelemetry SDK for obtaining the SDK version. The distribution version is taken from the [informational assembly version](https://learn.microsoft.com/en-us/dotnet/api/system.reflection.assemblyinformationalversionattribute?view=net-8.0), which can be obtained for self-contained projects too.
The existing approach for obtaining the assembly version fails for self-contained projects, as it's based on determining the assembly file.
=> Obtain distro version from the informational assembly version

CHANGELOG.md, src/Grafana.OpenTelemetry.Base/Instrumentations/AspNetCoreInitializer.cs
Fixes #71
With the 1.7.0 upstream ASP.NET Core instrumentation libraries, extension classes were renamed (open-telemetry/opentelemetry-dotnet#5161). This also requires updating class names used for lazy-loading in our distro. This PR updates the distro to use the new class names:
* `AspNetCoreInstrumentationTracerProviderBuilderExtensions`
* `AspNetCoreInstrumentationMeterProviderBuilderExtensions`
=> Adapt to upstream extension class name changes

CHANGELOG.md, src/Grafana.OpenTelemetry.Base/MeterProviderBuilderExtensions.cs
Fixes #74 
Sets `OTEL_DOTNET_EXPERIMENTAL_ASPNETCORE_ENABLE_GRPC_INSTRUMENTATION` to `true` when enabling tracing, similar to what was done for metrics in 0.7.0-beta.1
=> Enable experimental gRPC instrumentation when enabling tracing

CHANGELOG.md
Restores heading in CHANGELOG for 0.7.0-beta.2
=> Fix missing heading for release 0.7.0-beta.2

docker/docker-compose-aspnetcore/http/oats.http-get.yaml, docker/docker-compose-aspnetcore/http/oats.http-geterror.yaml, docker/docker-compose-aspnetcore/oats.http-get.yaml, docker/docker-compose-aspnetcore/oats.http-geterror.yaml, examples/net6.0/aspnetcore/Controllers/HttpClientController.cs, examples/net6.0/aspnetcore/Dockerfile, global.json
Updates build for .NET 8 SDK
Improves HTTP GET error controller action to return a 500, and adds OATs test looking for HTTP error span.
=> OATs build fixes, better HTTP error test

.github/workflows/oats.yml, scripts/run-oats-tests.sh
This adds a GH action for running OATS tests.
=> Add OATS tests to GH actions

.github/workflows/oats.yml, README.md
Updates the badge in the README to show the used OTel SDK with version 1.7.0
=> Increase OTel SDK badge version to 1.7.0

.github/workflows/oats.yml, README.md
Similar to the "Build" badge for unit tests, this adds an "OATS" badge showing whether OATS integration tests ran successfully for the `main` branch.
=> Add badge for OATS tests

CHANGELOG.md, README.md, docker/docker-compose-aspnetcore/attributes/oats-template.yml, docker/docker-compose-aspnetcore/attributes/oats.default-resource-attributes.yaml, docs/supported-instrumentations.md, src/Grafana.OpenTelemetry.Base/Grafana.OpenTelemetry.Base.csproj, src/Grafana.OpenTelemetry.Base/GrafanaOpenTelemetrySettings.cs, src/Grafana.OpenTelemetry.Base/Instrumentations/AWSResource.cs, src/Grafana.OpenTelemetry.Base/Instrumentations/AzureResource.cs, src/Grafana.OpenTelemetry.Base/Instrumentations/ContainerResource.cs, src/Grafana.OpenTelemetry.Base/Instrumentations/HostResource.cs, src/Grafana.OpenTelemetry.Base/Instrumentations/Instrumentation.cs, src/Grafana.OpenTelemetry.Base/Instrumentations/InstrumentationInitializer.cs, src/Grafana.OpenTelemetry.Base/Instrumentations/ProcessResource.cs, src/Grafana.OpenTelemetry.Base/Instrumentations/ProcessRuntimeResource.cs, tests/Grafana.OpenTelemetry.Tests/GrafanaOpenTelemetrySettingsTest.cs, tests/Grafana.OpenTelemetry.Tests/TracerProviderExtensionsTest.cs
Fixes grafana/app-o11y#651
This adds resource detectors for Azure, containers, hosts, processes, and process runtime.
=> Add all resource detectors from the .NET contrib repository

CHANGELOG.md, src/Grafana.OpenTelemetry.Base/Grafana.OpenTelemetry.Base.csproj, src/Grafana.OpenTelemetry/Grafana.OpenTelemetry.csproj
Upgrades ASP.NET Core an HTTP instrumentation to 1.7.1, Runtime to 1.7.0
=> Upgrades ASP.NET Core an HTTP instrumentation to 1.7.1, Runtime to 1.7.0

docs/configuration.md
Fixes a typo
I added `new` before `Uri`, allowing the code to compile without modification.
=> Add missing `new` before `Uri` in ExporterSettings

CHANGELOG.md, examples/net6.0/aspnetcore/aspnetcore.csproj, examples/net8.0/aspnetcore/aspnetcore.csproj, src/Grafana.OpenTelemetry.Base/Grafana.OpenTelemetry.Base.csproj, src/Grafana.OpenTelemetry.Base/Instrumentations/AWSResource.cs, src/Grafana.OpenTelemetry.Base/Instrumentations/InstrumentationInitializer.cs, src/Grafana.OpenTelemetry/Grafana.OpenTelemetry.csproj, src/Grafana.OpenTelemetry/OpenTelemetryBuilderExtension.cs
Upgrades SDK to 1.8.1 plus other packages that were out of date:
* Microsoft.Data.SqlClient
* OpenTelemetry.Exporter.Console
* OpenTelemetry.Exporter.OpenTelemetryProtocol
* OpenTelemetry.Extensions.Hosting
* OpenTelemetry.Instrumentation.AspNetCore
* OpenTelemetry.Instrumentation.EntityFrameworkCore
* OpenTelemetry.Instrumentation.GrpcNetClient
* OpenTelemetry.Instrumentation.Http
* OpenTelemetry.Instrumentation.Process
* OpenTelemetry.Instrumentation.Runtime
=> Upgrade to upstream SDK 1.8.1 (+ other dependencies)

docs/configuration.md, docs/supported-instrumentations.md
The MeterProvider variable is named `tracerProvider`, I have renamed it to `meterProvider`
Fixes #
Please provide a brief description of the changes here.
=> Correct typo in code example

CHANGELOG.md, src/Grafana.OpenTelemetry.Base/Grafana.OpenTelemetry.Base.csproj
See https://github.com/advisories/GHSA-hh2w-p6rv-4g7w
The distribution does not use the vulnerable method, but is installing the dependency, causing a warning.
=> Upgrade `System.Text.Json` to `8.0.4` for CVE-2024-30105

CHANGELOG.md, docs/supported-instrumentations.md, examples/net6.0/aspnetcore/aspnetcore.csproj, examples/net8.0/aspnetcore/aspnetcore.csproj, src/Grafana.OpenTelemetry.Base/Grafana.OpenTelemetry.Base.csproj, src/Grafana.OpenTelemetry.Base/Instrumentations/AWSResource.cs, src/Grafana.OpenTelemetry.Base/Instrumentations/AzureResource.cs, src/Grafana.OpenTelemetry.Base/Instrumentations/ContainerResource.cs, src/Grafana.OpenTelemetry.Base/Instrumentations/HostResource.cs, src/Grafana.OpenTelemetry.Base/Instrumentations/InstrumentationInitializer.cs, src/Grafana.OpenTelemetry.Base/Instrumentations/ProcessResource.cs, src/Grafana.OpenTelemetry.Base/Instrumentations/ProcessRuntimeResource.cs, src/Grafana.OpenTelemetry/Grafana.OpenTelemetry.csproj
Upgrades SDK to 1.9.0 plus other packages that were out of date:
* OpenTelemetry.Exporter.OpenTelemetryProtocol
* OpenTelemetry.Extensions.Hosting
* OpenTelemetry.Instrumentation.AspNet
* OpenTelemetry.Instrumentation.AspNetCore
* OpenTelemetry.Instrumentation.AWS
* OpenTelemetry.Instrumentation.AWSLambda
* OpenTelemetry.Instrumentation.EntityFrameworkCore
* OpenTelemetry.Instrumentation.GrpcNetClient
* OpenTelemetry.Instrumentation.Hangfire
* OpenTelemetry.Instrumentation.Http
* OpenTelemetry.Instrumentation.Owin
* OpenTelemetry.Instrumentation.Process
* OpenTelemetry.Instrumentation.Quartz
* OpenTelemetry.Instrumentation.Runtime
* OpenTelemetry.Instrumentation.SqlClient
* OpenTelemetry.Instrumentation.StackExchangeRedis
* OpenTelemetry.Instrumentation.Wcf
* OpenTelemetry.Resources.AWS
* …
=> Upgrade to upstream SDK 1.9.0 (+ other dependencies)

CHANGELOG.md, src/Grafana.OpenTelemetry.Base/GrafanaOpenTelemetrySettings.cs, src/Grafana.OpenTelemetry.Base/ResourceBuilderExtension.cs, tests/Grafana.OpenTelemetry.Tests/GrafanaOpenTelemetrySettingsTest.cs, tests/Grafana.OpenTelemetry.Tests/ResourceBuilderExtensionTest.cs
Remove workaround for stable `service.instance.id` across signals
=> Remove workaround for stable service.instance.id across signals

.github/workflows/oats.yml
Bump Go version for OATs integration tests
* ~[ ] Unit tests added/updated~
* ~[ ] [`CHANGELOG.md`](https://github.com/grafana/grafana-opentelemetry-dotnet) file updated for non-trivial changes~
* ~[ ] Changes in public API reviewed (if applicable)~
=> Bump Go version for OATs integration tests

.github/workflows/unit-tests.yml, CHANGELOG.md, tests/Grafana.OpenTelemetry.Tests/Grafana.OpenTelemetry.Tests.csproj
Removes .NET 7.0 build target and CI. Support for .NET 7 ended May 24 2024
=> Removes .NET 7.0 build target and CI

CHANGELOG.md, src/Grafana.OpenTelemetry.Base/Grafana.OpenTelemetry.Base.csproj, src/Grafana.OpenTelemetry.Base/ResourceDetectors/AWSEBSDetectorInitializer.cs, src/Grafana.OpenTelemetry.Base/ResourceDetectors/AWSEC2DetectorInitializer.cs, src/Grafana.OpenTelemetry.Base/ResourceDetectors/AWSECSDetectorInitializer.cs, src/Grafana.OpenTelemetry.Base/ResourceDetectors/AWSEKSDetectorInitializer.cs, src/Grafana.OpenTelemetry.Base/ResourceDetectors/AzureAppServiceDetectorInitializer.cs, src/Grafana.OpenTelemetry.Base/ResourceDetectors/AzureContainerAppsDetectorInitializer.cs, src/Grafana.OpenTelemetry.Base/ResourceDetectors/AzureVMDetectorInitializer.cs
Removes AWS and Azure cloud resource detectors. This is a breaking change.
These detectors are being removed from the package to prevent application startup issues. These detectors attempt to determine which cloud platform an application is deployed to, and this can significantly impact startup times.
Configuration documentation changes to follow.
=> Removes AWS and Azure cloud resource detectors

src/Grafana.OpenTelemetry.Base/GrafanaOpenTelemetrySettings.cs
Rename resource detector configuration environment variables to align with existing scheme (ex OTEL_RESOURCE_ATTRIBUTES, OTEL_NODE_RESOURCE_DETECTORS).
=> Rename resource detector configuration environment variables

CHANGELOG.md, src/Grafana.OpenTelemetry.Base/Grafana.OpenTelemetry.Base.csproj
Update host and OS detectors for 1.0.1
=> Update host and OS detectors for 1.0.1

CHANGELOG.md, docs/supported-instrumentations.md, src/Grafana.OpenTelemetry.Base/Grafana.OpenTelemetry.Base.csproj, src/Grafana.OpenTelemetry.Base/Instrumentations/MySqlDataInitializer.cs
Fixes #
Remove dependency on Mysql.Data.OpenTelemetry
=> Remove dependency on Mysql.Data.OpenTelemetry

CHANGELOG.md
Correct overwritten CHANGELOG entry for 1.1.0
=> Correct overwritten CHANGELOG entry for 1.1.0

tests/Grafana.OpenTelemetry.Tests/Grafana.OpenTelemetry.Tests.csproj
Avoid error running `dotnet test` by removing non-runnable TFM.
=> Remove netstandard from tests

README.md, docs/migration.md
Users should install the latest stable release now there is one.
=> Remove prerelease flag

.github/renovate.json
Fixes #167.
Remove trailing `,`.
=> Fix Renovate configuration

examples/net8.0/aspnetcore/Dockerfile
Use the Ubuntu Noble chiselled container to reduce the size of the test container by ~30%.
=> Use chiseled container

.github/workflows/ci.yml
- Only generate on Windows (as that's the "chosen one" for publishing).
- Rename to `grafana-opentelemetry-dotnet.spdx.json`.
=> Refactor SBOM generation

.github/renovate.json
Modify renovate recommended `ignoredPaths` to allow updates in ./tests and ./examples. The NuGet matcher already examines ./tests, but it does not appear other matchers do.
Default `ignorePaths`: https://docs.renovatebot.com/presets-default/#ignoremodulesandtests
=> adjust ignorePaths to pick up .NET examples

CHANGELOG.md, docs/supported-instrumentations.md, src/Grafana.OpenTelemetry/Grafana.OpenTelemetry.csproj
Fixes #124
- Remove deprecated `OpenTelemetry.Instrumentation.MySqlData` package.
- Update `OpenTelemetry.Instrumentation.Wcf` to `1.0.0-rc.18`.
=> Remove deprecated packages

src/Grafana.OpenTelemetry.Base/GrafanaOpenTelemetryEventSource.cs, src/Grafana.OpenTelemetry.Base/GrafanaOpenTelemetrySettings.cs, src/Grafana.OpenTelemetry.Base/Instrumentations/InstrumentationInitializer.cs, src/Grafana.OpenTelemetry.Base/Instrumentations/SqlClientInitializer.cs
Contributes to #97.
Address some native AoT warnings with .NET 8.
The only remaining warning is from the usage of `ReflectionHelper.CallStaticMethod()`.
Need to update the documentation to state somewhere that SQL instrumentation is not enabled when using native AoT.
=> Address some native AoT warnings

examples/net8.0/aspnetcore/TodoAppEndpoints.cs, src/Grafana.OpenTelemetry.Base/ExporterSettings/AgentOtlpExporter.cs, src/Grafana.OpenTelemetry.Base/ExporterSettings/CloudOtlpExporter.cs, src/Grafana.OpenTelemetry.Base/ExporterSettings/GrafanaCloudConfigurationHelper.cs, src/Grafana.OpenTelemetry.Base/ExporterSettings/OtlpExporter.cs, src/Grafana.OpenTelemetry.Base/GrafanaOpenTelemetryResourceDetector.cs, src/Grafana.OpenTelemetry.Base/Instrumentations/InstrumentationInitializer.cs, src/Grafana.OpenTelemetry.Base/ResourceBuilderExtension.cs, src/Grafana.OpenTelemetry.Base/ResourceDetectors/ResourceDetectorInitializer.cs, tests/Grafana.OpenTelemetry.Tests/Grafana.OpenTelemetry.Tests.csproj, tests/Grafana.OpenTelemetry.Tests/OpenTelemetryLoggerOptionsExtensionsTest.cs, tests/Grafana.OpenTelemetry.Tests/TracerProviderExtensionsTest.cs
Fix CodeQL suggestions, which mostly fall into the "minor code analysis warnings" category and a few style ones, plus one bug in the example app.
=> Fix CodeQL warnings

.github/copilot-instructions.md, README.md
Explain how the value of `OTEL_EXPORTER_OTLP_HEADERS` is derived.
=> Explain OTEL_EXPORTER_OTLP_HEADERS

docker/docker-compose-aspnetcore/oats.yaml
- Require 1 or more, rather than zero or more.
- Add `http_server_request_duration_seconds_count`.
=> Update OATS metrics

CHANGELOG.md, docker/docker-compose-aspnetcore/oats.yaml, examples/net8.0/aspnetcore/aspnetcore.csproj, src/Grafana.OpenTelemetry.Base/Grafana.OpenTelemetry.Base.csproj, src/Grafana.OpenTelemetry.Base/GrafanaOpenTelemetryEventSource.cs, src/Grafana.OpenTelemetry.Base/Instrumentations/SqlClientInitializer.cs, src/Grafana.OpenTelemetry/Grafana.OpenTelemetry.csproj
Update OpenTelemetry (and test) NuGet packages to their latest versions.
- Resolves #173.
- Resolves https://github.com/grafana/grafana-opentelemetry-dotnet/security/dependabot/9.
- Resolves https://github.com/grafana/grafana-opentelemetry-dotnet/security/dependabot/10.
- Resolves https://github.com/grafana/grafana-opentelemetry-dotnet/security/code-scanning/26.
This raises a few questions:
1. .NET 9 `Microsoft.Extensions.*` dependencies are forced onto .NET 8 applications (https://github.com/open-telemetry/opentelemetry-dotnet-contrib/issues/2361).
- I'm sure I saw an issue somewhere regarding the LTS-supported-ness of these related to Aspire, so I need to dig that out and determine if we need to either accept that change (and force it on our users), or push back upstream on the 9.0 …
=> Update OpenTelemetry package versions

CHANGELOG.md, src/Grafana.OpenTelemetry.Base/Instrumentations/CassandraInitializer.cs, src/Grafana.OpenTelemetry/Grafana.OpenTelemetry.csproj
- Bump CassandraCSharpDriver to 3.22.0.
- Add support for tracing to Cassandra.
=> Add tracing for Cassandra

CHANGELOG.md, src/Grafana.OpenTelemetry/Grafana.OpenTelemetry.csproj
Bump OpenTelemetry.Instrumentation.ElasticsearchClient to the latest version.
=> Bump OpenTelemetry.Instrumentation.ElasticsearchClient

.github/workflows/dotnet-format.yml
Explicitly install the .NET SDK so the version is deterministic and not dependent on whatever version is installed on the GitHub Actions runner.
=> Install .NET SDK

.github/workflows/ci.yml
Publish NuGet packages built on main or from tags to feedz.io.
=> Publish to feedz.io

README.md
Add a note to the README about how to consume prerelease packages from feedz.io now #186 was merged.
=> Add prerelease package notes

.config/dotnet-tools.json, .github/workflows/ci.yml
Use a .NET tools manifest to manage the version of dotnet-validate, which then can be updated by renovate.
Also bumps the version to `0.0.1-preview.537`.
=> Use tools manifest for dotnet-validate version

.github/renovate.json
Ignore the `:ignoreModulesAndTests` preset so tests get updated.
=> Fix renovate not updating tests
