src/Grafana.OpenTelemetry.Base/Grafana.OpenTelemetry.Base.csproj, src/Grafana.OpenTelemetry/Grafana.OpenTelemetry.csproj
Update to newest available instrumentation library versions.
=> Updating package versions

README.md, docs/configuration.md, docs/supported-instrumentations.md
* ~~[ ] [`CHANGELOG.md`](https://github.com/grafana/grafana-opentelemetry-dotnet) file updated for non-trivial changes~~
=> Minor spelling and punctuation fixes in documentation

docs/migration.md
Adds upstream migration guide instructions.
=> Adds upstream migration guide

README.md, docs/configuration.md
* ~~Remove the "Cloud" in "Grafana Cloud Application Observability" to be consistent with Grafana docs.~~
* Add documentation of how to obtain values for zone, instance ID, and API token.
* ~~[ ] [`CHANGELOG.md`](https://github.com/grafana/grafana-opentelemetry-dotnet) file updated for non-trivial changes~~
=> Consistency with Grafana documentation

CHANGELOG.md
Preparation for a 0.6.0-beta.2 release.
=> Preparation for the 0.6.0-beta.2 release

CHANGELOG.md
Update CHANGELOG for 0.6.0-beta.3
=> Update CHANGELOG for 0.6.0-beta.3

CHANGELOG.md, examples/net6.0/aspnetcore/aspnetcore.csproj, src/Grafana.OpenTelemetry.Base/Grafana.OpenTelemetry.Base.csproj, src/Grafana.OpenTelemetry.Base/TracerProviderBuilderExtensions.cs, src/Grafana.OpenTelemetry/Grafana.OpenTelemetry.csproj
Upgrade to version 1.7.0 of:
* `OpenTelemetry`
* `OpenTelemetry.Exporter.OpenTelemetryProtocol`
* `OpenTelemetry.Extensions.Hosting`
* `OpenTelemetry.Instrumentation.AspNetCore`
* `OpenTelemetry.Instrumentation.Http`
=> Upgrade core packages to 1.7.0

CHANGELOG.md
Update CHANGELOG for 0.7.0-beta.2
=> Update CHANGELOG for 0.7.0-beta.2

CHANGELOG.md
Update CHANGELOG for 0.7.0-beta.3
=> Update CHANGELOG for 0.7.0-beta.3

src/Grafana.OpenTelemetry.Base/Grafana.OpenTelemetry.Base.csproj, src/Grafana.OpenTelemetry.Base/Instrumentations/AWSResource.cs, src/Grafana.OpenTelemetry.Base/Instrumentations/InstrumentationInitializer.cs
Fixes #
Please provide a brief description of the changes here.
=> Remove warnings around AWS resource detectors

CHANGELOG.md
Update CHANGELOG for 0.8.1-beta.1
=> Update CHANGELOG for 0.8.1-beta.1

CHANGELOG.md
#	CHANGELOG.md
Fixes #
Please provide a brief description of the changes here.
=> Update CHANGELOG for 0.8.2-beta.1

CHANGELOG.md
Mark CHANGELOG entries for 0.9.0-beta.1
=> Update CHANGELOG with release version

.github/CODEOWNERS
Replaces individual accounts with `@grafana/otel-sdk` team
=> Switch CODEOWNERS to team

CHANGELOG.md, src/Grafana.OpenTelemetry.Base/Grafana.OpenTelemetry.Base.csproj, src/Grafana.OpenTelemetry.Base/ResourceDetectors/OperatingSystemResourceInitializer.cs, src/Grafana.OpenTelemetry.Base/ResourceDetectors/ResourceDetector.cs, src/Grafana.OpenTelemetry.Base/ResourceDetectors/ResourceDetectorInitializer.cs, tests/Grafana.OpenTelemetry.Tests/ResourceDetectorTest.cs
Adds OperatingSystem resource detector
=> Adds OperatingSystem resource detector

src/Grafana.OpenTelemetry.Base/ResourceDetectors/OperatingSystemResourceInitializer.cs, src/Grafana.OpenTelemetry.Base/ResourceDetectors/ResourceDetector.cs
=> Fixes OS detector ID

docker/docker-compose-aspnetcore/attributes/oats-template.yml, docker/docker-compose-aspnetcore/http/oats-template.yaml, docker/docker-compose-aspnetcore/oats-template.yml, docker/docker-compose-aspnetcore/redis/oats-template.yaml
based on https://github.com/grafana/oats/pull/43
=> use docker-lgtm for integration tests

README.md, docs/configuration.md, docs/installation.md, docs/supported-resource-detectors.md, src/Grafana.OpenTelemetry.Base/ResourceDetectors/AWSEBSDetectorInitializer.cs, src/Grafana.OpenTelemetry.Base/ResourceDetectors/AWSEC2DetectorInitializer.cs, src/Grafana.OpenTelemetry.Base/ResourceDetectors/AWSECSDetectorInitializer.cs, src/Grafana.OpenTelemetry.Base/ResourceDetectors/AWSEKSDetectorInitializer.cs, src/Grafana.OpenTelemetry.Base/ResourceDetectors/AzureAppServiceDetectorInitializer.cs, src/Grafana.OpenTelemetry.Base/ResourceDetectors/AzureContainerAppsDetectorInitializer.cs, src/Grafana.OpenTelemetry.Base/ResourceDetectors/AzureVMDetectorInitializer.cs, src/Grafana.OpenTelemetry.Base/ResourceDetectors/ResourceDetector.cs, tests/Grafana.OpenTelemetry.Tests/ResourceDetectorTest.cs
Updates installation and configuration documentation for GA release.
Covers new resource detector support.
=> Updates installation and configuration documentation for GA release

CHANGELOG.md
CHANGELOG entries for 1.0.0 release.
=> 1.0.0 CHANGELOG

src/Grafana.OpenTelemetry.Base/Grafana.OpenTelemetry.Base.csproj
Bumps reference for System.Text.Json to resolve https://github.com/advisories/GHSA-8g4q-xg66-9fp4
=> Resolve CVE-2024-43485

src/Grafana.OpenTelemetry.Base/Grafana.OpenTelemetry.Base.csproj
Update packages to last minor revs before 1.10.0 SDK upgrade
=> Update packages to last minor revs before 1.10.0 SDK upgrade

.github/workflows/dotnet-format.yml, .github/workflows/markdown-link-check.yml, .github/workflows/markdownlint.yml, .github/workflows/misspell.yml, .github/workflows/oats.yml, .github/workflows/unit-tests.yml
Applies zizmor recommendations.
=> Applies zizmor recommendations

renovate.json
Enable auto-merge as the behaviour appears to be correct.
=> Enable renovate auto-merge

CHANGELOG.md
Split CHANGELOG in to breaking/new/bug fixes
=> Revise CHANGELOG for 1.12
